# Generated by Django 4.0.4 on 2022-06-05 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='famiia',
            fields=[
                ('id', models.CharField(default=uuid.UUID('45b16401-a700-44af-92ae-9fe27b62406c'), max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('cumpleaños', models.IntegerField()),
            ],
        ),
    ]
